### ISSUE TITLE
Can the joystick movement be supported?

### ISSUE THREAD

**Issue by lpf696** [bfeber/HLA-NoVR#149] opened 2023-07-02 14:26 UTC
Dear bfeber:
      My English is not very good, please forgive my Syntax error,Thanks!
      I hope to use the joystick to control movement in VR mode. Can I achieve this?
      If possible, I hope to sponsor you to give you time to complete this work. Can you contact me? My email address 391795732@qq.com Thank you again!

**Comment by bfeber** [comment] 2023-10-06 10:22
Duplicate of #52

**Closed by bfeber** 2023-10-06 10:22 UTC
