### ISSUE TITLE
Object stuck in the air, necessary to move forward in story (Chapter 3, train)

### ISSUE THREAD

**Issue by Clubdidu** [bfeber/HLA-NoVR#123] opened 2023-04-22 10:58 UTC
I have a problem, an object which is necessary to move forward in story is stuck in the air. When i want to move it, it just moves very slightly but is sticked to the position in the picture. What can i do?

![object stuck](https://user-images.githubusercontent.com/65295513/233780099-606a44f3-24b4-43a5-8ba2-313ec2e11343.png)

**Comment by bfeber** [comment] 2023-04-22 11:00
Duplicate of #92, will fix soon. Just reload an earlier save.

**Closed by bfeber** 2023-04-22 11:00 UTC
